### ISSUE TITLE
ability to activate modules with triggers

### ISSUE THREAD

**Issue by McDiod** [DerZade/BackpackOnChest#14]
pls

**Comment by DerZade** [comment]
I actually don't see the point of doing that, although I think this can be achieved by just some little changes in the [config of those modules](https://github.com/DerZade/BackpackOnChest/blob/master/addons/zade_boc/CfgVehicles.hpp). 
@McDiod If you want to you can commit those changes by yourself and I will include the whole thing in the next update.

**Comment by McDiod** [comment]
#15

**Comment by DerZade** [comment]
@McDiod Thank you very much.
