### ISSUE TITLE
Error when syncing units without backpack to zade_boc_moduleOnChest

### ISSUE THREAD

**Issue by Synch2k** [DerZade/BackpackOnChest#17]
BOC throws an error when units without a backpack are synced with the module http://i.imgur.com/n5K4LR4.png
Every unit after the one causing the error will not be processed anymore
please catch the error for enhanced usability

**Comment by DerZade** [comment]
https://github.com/DerZade/BackpackOnChest/commit/f892fecb11270770892551f98c74a439d0f15b37
