### ISSUE TITLE
BackpackonChest remains after death

### ISSUE THREAD

**Issue by Kompetenzteam** [DerZade/BackpackOnChest#21]
When dying with BackpackonChest and respawning, there`s no BackpackonChest after respawn (OK) but in ACE3 Menu you can "Switch Backpacks" and then suddenly the Backpack which was on Chest before death reappears.... sometimes the invisible Backpack after respawn prevents from running too!

**Comment by DerZade** [comment]
@Kompetenzteam Do you know which configuration for the respawn/respawntemplate you used ?

**Comment by Kompetenzteam** [comment]
Nothing special. Bwmod, ace3, default modules. Respawn=3, rhs, spyderaddons loadoutmanager.  Will test today  again 




On Fri, Mar 31, 2017 at 6:43 PM +0200, "DerZade" <notifications@github.com> wrote:












@Kompetenzteam Do you know which configuration for the respawn/respawntemplate you used ?

**Comment by DerZade** [comment]
@Kompetenzteam I tried it several times and with several settings but couldn't reproduce the issue.
